limit_req_zone $binary_remote_addr zone=astrosferum_general:1m rate=20r/s;
limit_req_zone $binary_remote_addr zone=astrosferum_login:1m rate=6r/m;
limit_req_zone $binary_remote_addr zone=astrosferum_admission:1m rate=6r/m;
