package astronomy

import (
	"fmt"
	"math"
	"time"

	"bot_astrosferum/internal/forecast"
)

const CelestialEphemerisVersion = "celestial-horizontal-distance-aspect-jpl-meeus-wgs84-h0-v3"

var (
	// The common reception-time domain starts one UTC day after the nominal
	// Pluto-series boundary so the retarded Pluto state remains within its
	// published source interval for every accepted instant.
	celestialEphemerisFirstInstant = time.Date(1885, time.January, 2, 0, 0, 0, 0, time.UTC)
	celestialEphemerisLastInstant  = time.Date(2050, time.January, 1, 0, 0, 0, 0, time.UTC)
)

type CelestialBody string

const (
	CelestialSun     CelestialBody = "sun"
	CelestialMoon    CelestialBody = "moon"
	CelestialMercury CelestialBody = "mercury"
	CelestialVenus   CelestialBody = "venus"
	CelestialMars    CelestialBody = "mars"
	CelestialJupiter CelestialBody = "jupiter"
	CelestialSaturn  CelestialBody = "saturn"
	CelestialUranus  CelestialBody = "uranus"
	CelestialNeptune CelestialBody = "neptune"
	CelestialPluto   CelestialBody = "pluto"
	celestialEarth   CelestialBody = "earth"
)

var celestialBodyOrder = [...]CelestialBody{
	CelestialSun,
	CelestialMoon,
	CelestialMercury,
	CelestialVenus,
	CelestialMars,
	CelestialJupiter,
	CelestialSaturn,
	CelestialUranus,
	CelestialNeptune,
	CelestialPluto,
}

func CelestialBodies() []CelestialBody {
	bodies := celestialBodyOrder
	return bodies[:]
}

type CelestialHorizontalPosition struct {
	ValidAt                  time.Time     `json:"valid_at"`
	Body                     CelestialBody `json:"body"`
	AzimuthDegrees           float64       `json:"azimuth_deg"`
	GeometricAltitudeDegrees float64       `json:"geometric_altitude_deg"`
	ApparentAltitudeDegrees  float64       `json:"apparent_altitude_deg"`
	ReferenceDistanceKM      float64       `json:"reference_distance_km"`
	DistanceClosenessPercent float64       `json:"distance_closeness_percent"`
	RadialVelocityKMS        float64       `json:"radial_velocity_km_s"`
	SaturnRingOpeningDegrees *float64      `json:"saturn_ring_opening_deg,omitempty"`
}

// CelestialDistanceScale is the deterministic model-wide geocentric distance
// range over the common half-open planning domain.  It is not a 72-hour or a
// nearest-opposition normalization.  The extrema are located from the same
// ephemeris implementation used for each published sample.
type CelestialDistanceScale struct {
	DomainStart        time.Time `json:"domain_start"`
	DomainEndExclusive time.Time `json:"domain_end_exclusive"`
	SampleStepHours    int       `json:"sample_step_hours"`
	ReferenceCenter    string    `json:"reference_center"`
	MinimumKM          float64   `json:"minimum_km"`
	MinimumAt          time.Time `json:"minimum_at"`
	MaximumKM          float64   `json:"maximum_km"`
	MaximumAt          time.Time `json:"maximum_at"`
}

type CelestialTrack struct {
	Body                         CelestialBody                 `json:"body"`
	DistanceScale                CelestialDistanceScale        `json:"distance_scale"`
	MeanDistanceClosenessPercent int                           `json:"mean_distance_closeness_percent"`
	Samples                      []CelestialHorizontalPosition `json:"samples"`
}

const (
	celestialReferenceEarthCenter         = "earth_center"
	celestialReferenceEarthMoonBarycentre = "earth_moon_barycentre"
)

// celestialHourlyDistanceScales is generated by the exhaustive test helper
// over every whole UTC hour in the common half-open planning domain.  It is a
// finite sampled model range, not a claim about continuous physical extrema.
var celestialHourlyDistanceScales = map[CelestialBody]CelestialDistanceScale{
	CelestialSun: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthCenter,
		MinimumKM: 147091300.209057, MinimumAt: time.Date(1886, time.January, 1, 10, 0, 0, 0, time.UTC), MaximumKM: 152104776.967279, MaximumAt: time.Date(1885, time.July, 2, 19, 0, 0, 0, time.UTC),
	},
	CelestialMoon: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthCenter,
		MinimumKM: 356379.975697704, MinimumAt: time.Date(1912, time.January, 4, 14, 0, 0, 0, time.UTC), MaximumKM: 406710.901155577, MaximumAt: time.Date(1984, time.March, 2, 11, 0, 0, 0, time.UTC),
	},
	CelestialMercury: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 82137448.5859165, MinimumAt: time.Date(2015, time.May, 31, 3, 0, 0, 0, time.UTC), MaximumKM: 217146742.587838, MaximumAt: time.Date(2034, time.December, 3, 14, 0, 0, 0, time.UTC),
	},
	CelestialVenus: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 39583155.5808154, MinimumAt: time.Date(1890, time.December, 4, 8, 0, 0, 0, time.UTC), MaximumKM: 259690185.261476, MaximumAt: time.Date(1960, time.June, 21, 23, 0, 0, 0, time.UTC),
	},
	CelestialMars: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 55765033.9175095, MinimumAt: time.Date(1924, time.August, 22, 23, 0, 0, 0, time.UTC), MaximumKM: 400347767.825911, MaximumAt: time.Date(1987, time.August, 23, 13, 0, 0, 0, time.UTC),
	},
	CelestialJupiter: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 591106110.333668, MinimumAt: time.Date(1951, time.October, 2, 6, 0, 0, 0, time.UTC), MaximumKM: 965582824.457831, MaximumAt: time.Date(1957, time.October, 4, 9, 0, 0, 0, time.UTC),
	},
	CelestialSaturn: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 1202232274.58798, MinimumAt: time.Date(1885, time.December, 26, 8, 0, 0, 0, time.UTC), MaximumKM: 1651251630.47091, MaximumAt: time.Date(1929, time.December, 25, 0, 0, 0, 0, time.UTC),
	},
	CelestialUranus: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 2586417270.75852, MinimumAt: time.Date(1967, time.March, 14, 13, 0, 0, 0, time.UTC), MaximumKM: 3155265876.66791, MaximumAt: time.Date(1925, time.March, 13, 12, 0, 0, 0, time.UTC),
	},
	CelestialNeptune: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 4311418229.12147, MinimumAt: time.Date(2043, time.November, 2, 22, 0, 0, 0, time.UTC), MaximumKM: 4685172832.46088, MaximumAt: time.Date(1961, time.November, 2, 20, 0, 0, 0, time.UTC),
	},
	CelestialPluto: {
		DomainStart: celestialEphemerisFirstInstant, DomainEndExclusive: celestialEphemerisLastInstant, SampleStepHours: 1, ReferenceCenter: celestialReferenceEarthMoonBarycentre,
		MinimumKM: 4291499505.66273, MinimumAt: time.Date(1990, time.May, 7, 23, 0, 0, 0, time.UTC), MaximumKM: 7409024363.87804, MaximumAt: time.Date(1885, time.May, 22, 11, 0, 0, 0, time.UTC),
	},
}

func (body CelestialBody) isPlanet() bool {
	switch body {
	case CelestialMercury, CelestialVenus, CelestialMars, CelestialJupiter,
		CelestialSaturn, CelestialUranus, CelestialNeptune, CelestialPluto:
		return true
	default:
		return false
	}
}

func ComputeCelestialTracks(location forecast.Location, validTimes []time.Time) ([]CelestialTrack, error) {
	if err := forecast.ValidateCoordinates(location.Latitude, location.Longitude); err != nil {
		return nil, err
	}
	if len(validTimes) == 0 {
		return nil, fmt.Errorf("celestial tracks require at least one instant")
	}
	if err := validateCelestialTrackTimes(validTimes); err != nil {
		return nil, err
	}
	tracks := make([]CelestialTrack, len(celestialBodyOrder))
	for bodyIndex, body := range celestialBodyOrder {
		distanceScale, err := celestialDistanceScale(body)
		if err != nil {
			return nil, fmt.Errorf("compute %s distance scale: %w", body, err)
		}
		tracks[bodyIndex] = CelestialTrack{
			Body: body, DistanceScale: distanceScale,
			Samples: make([]CelestialHorizontalPosition, len(validTimes)),
		}
		for timeIndex, validAt := range validTimes {
			position, err := CelestialPositionAt(location, validAt, body)
			if err != nil {
				return nil, fmt.Errorf("compute %s at %s: %w", body, validAt.Format(time.RFC3339), err)
			}
			tracks[bodyIndex].Samples[timeIndex] = position
		}
		tracks[bodyIndex].MeanDistanceClosenessPercent = meanDistanceClosenessPercent(tracks[bodyIndex].Samples)
	}
	if err := ValidateCelestialTracks(tracks, validTimes); err != nil {
		return nil, err
	}
	return tracks, nil
}

func ValidateCelestialTracks(tracks []CelestialTrack, validTimes []time.Time) error {
	if err := validateCelestialTrackTimes(validTimes); err != nil {
		return err
	}
	if len(tracks) != len(celestialBodyOrder) {
		return fmt.Errorf("celestial track count is %d, want %d", len(tracks), len(celestialBodyOrder))
	}
	for trackIndex, track := range tracks {
		body := celestialBodyOrder[trackIndex]
		if track.Body != body || len(track.Samples) != len(validTimes) {
			return fmt.Errorf("celestial track %d identity or cardinality is invalid", trackIndex)
		}
		wantScale, err := celestialDistanceScale(body)
		if err != nil {
			return fmt.Errorf("celestial track %s distance scale: %w", body, err)
		}
		if track.DistanceScale != wantScale {
			return fmt.Errorf("celestial track %s distance scale is invalid", body)
		}
		for sampleIndex, sample := range track.Samples {
			if sample.Body != body || !sample.ValidAt.Equal(validTimes[sampleIndex]) {
				return fmt.Errorf("celestial track %s sample %d identity or time is invalid", body, sampleIndex)
			}
			if err := validateCelestialPosition(sample); err != nil {
				return fmt.Errorf("celestial track %s sample %d: %w", body, sampleIndex, err)
			}
		}
		wantMean := meanDistanceClosenessPercent(track.Samples)
		if track.MeanDistanceClosenessPercent < 0 || track.MeanDistanceClosenessPercent > 100 ||
			track.MeanDistanceClosenessPercent != wantMean {
			return fmt.Errorf("celestial track %s mean distance closeness is invalid", body)
		}
	}
	return nil
}

func validateCelestialTrackTimes(validTimes []time.Time) error {
	if len(validTimes) == 0 {
		return fmt.Errorf("celestial tracks require at least one instant")
	}
	for index, validAt := range validTimes {
		utc := validAt.UTC()
		if validAt.IsZero() || utc.Minute() != 0 || utc.Second() != 0 || utc.Nanosecond() != 0 {
			return fmt.Errorf("celestial track time %d is not an exact UTC hour", index)
		}
		if err := validateCelestialEphemerisInstant(utc); err != nil {
			return fmt.Errorf("celestial track time %d: %w", index, err)
		}
		if index > 0 && utc.Sub(validTimes[index-1].UTC()) != time.Hour {
			return fmt.Errorf("celestial track times %d and %d are not exactly one hour apart", index-1, index)
		}
	}
	return nil
}

func CelestialPositionAt(location forecast.Location, at time.Time, body CelestialBody) (CelestialHorizontalPosition, error) {
	position := CelestialHorizontalPosition{ValidAt: at.UTC(), Body: body}
	if at.IsZero() {
		return position, fmt.Errorf("celestial position time is zero")
	}
	if err := validateCelestialEphemerisInstant(at); err != nil {
		return position, err
	}
	if err := forecast.ValidateCoordinates(location.Latitude, location.Longitude); err != nil {
		return position, err
	}
	if body == CelestialMoon {
		state := MoonStateAt(location, at)
		if !state.Valid {
			return position, fmt.Errorf("lunar ephemeris is unavailable")
		}
		position.AzimuthDegrees = state.AzimuthDegrees
		position.GeometricAltitudeDegrees = state.TopocentricGeometricAltitudeDegrees
		position.ApparentAltitudeDegrees = planningApparentAltitude(state.TopocentricGeometricAltitudeDegrees*degree) / degree
		position.ReferenceDistanceKM = state.EarthMoonDistanceKM
	} else {
		var coordinates equatorial
		var err error
		switch body {
		case CelestialSun:
			coordinates = sunCoordinates(at)
		case CelestialMercury, CelestialVenus, CelestialMars, CelestialJupiter, CelestialSaturn, CelestialUranus, CelestialNeptune, CelestialPluto:
			coordinates, err = planetCoordinates(at, body)
		default:
			return position, fmt.Errorf("unsupported celestial body %q", body)
		}
		if err != nil {
			return position, err
		}
		altitude, azimuth := topocentricHorizontal(at, location, coordinates)
		position.AzimuthDegrees = normalizeRadians(azimuth) / degree
		position.GeometricAltitudeDegrees = altitude / degree
		position.ApparentAltitudeDegrees = planningApparentAltitude(altitude) / degree
		position.ReferenceDistanceKM = coordinates.distance
	}
	distanceScale, err := celestialDistanceScale(body)
	if err != nil {
		return position, err
	}
	position.DistanceClosenessPercent, err = distanceClosenessPercent(position.ReferenceDistanceKM, distanceScale)
	if err != nil {
		return position, err
	}
	position.RadialVelocityKMS, err = celestialRadialVelocityKMS(at, body)
	if err != nil {
		return position, err
	}
	if body == CelestialSaturn {
		opening, openingErr := saturnRingOpeningDegrees(at)
		if openingErr != nil {
			return position, openingErr
		}
		position.SaturnRingOpeningDegrees = &opening
	}
	return position, validateCelestialPosition(position)
}

func validateCelestialEphemerisInstant(at time.Time) error {
	instant := at.UTC()
	if instant.Before(celestialEphemerisFirstInstant) || !instant.Before(celestialEphemerisLastInstant) {
		return fmt.Errorf("celestial planning ephemeris supports instants from %s through but excluding %s", celestialEphemerisFirstInstant.Format(time.DateOnly), celestialEphemerisLastInstant.Format(time.DateOnly))
	}
	return nil
}

func validateCelestialPosition(position CelestialHorizontalPosition) error {
	if position.ValidAt.IsZero() || !finite(position.AzimuthDegrees) || position.AzimuthDegrees < 0 || position.AzimuthDegrees >= 360 ||
		!finite(position.GeometricAltitudeDegrees) || position.GeometricAltitudeDegrees < -90 || position.GeometricAltitudeDegrees > 90 ||
		!finite(position.ApparentAltitudeDegrees) || position.ApparentAltitudeDegrees < -90 || position.ApparentAltitudeDegrees > 90 ||
		!finite(position.ReferenceDistanceKM) || position.ReferenceDistanceKM <= 0 ||
		!finite(position.DistanceClosenessPercent) || position.DistanceClosenessPercent < 0 || position.DistanceClosenessPercent > 100 ||
		!finite(position.RadialVelocityKMS) {
		return fmt.Errorf("%s horizontal ephemeris is outside its physical range", position.Body)
	}
	if position.Body == CelestialSaturn {
		if position.SaturnRingOpeningDegrees == nil || !finite(*position.SaturnRingOpeningDegrees) ||
			*position.SaturnRingOpeningDegrees < -90 || *position.SaturnRingOpeningDegrees > 90 {
			return fmt.Errorf("saturn ring opening is outside its physical range")
		}
	} else if position.SaturnRingOpeningDegrees != nil {
		return fmt.Errorf("%s unexpectedly carries a Saturn ring opening", position.Body)
	}
	return nil
}

func celestialDistanceScale(body CelestialBody) (CelestialDistanceScale, error) {
	scale, ok := celestialHourlyDistanceScales[body]
	if !ok {
		return CelestialDistanceScale{}, fmt.Errorf("unsupported celestial body %q", body)
	}
	wantReferenceCenter := celestialReferenceEarthCenter
	if body.isPlanet() {
		wantReferenceCenter = celestialReferenceEarthMoonBarycentre
	}
	if scale.DomainStart != celestialEphemerisFirstInstant || scale.DomainEndExclusive != celestialEphemerisLastInstant ||
		scale.SampleStepHours != 1 || !finite(scale.MinimumKM) || !finite(scale.MaximumKM) ||
		scale.MinimumKM <= 0 || scale.MaximumKM <= scale.MinimumKM || scale.ReferenceCenter != wantReferenceCenter ||
		!validDistanceScaleExtremumTime(scale.MinimumAt) || !validDistanceScaleExtremumTime(scale.MaximumAt) {
		return CelestialDistanceScale{}, fmt.Errorf("%s hourly distance scale is invalid", body)
	}
	return scale, nil
}

func validDistanceScaleExtremumTime(at time.Time) bool {
	utc := at.UTC()
	return !utc.Before(celestialEphemerisFirstInstant) && utc.Before(celestialEphemerisLastInstant) &&
		utc.Minute() == 0 && utc.Second() == 0 && utc.Nanosecond() == 0
}

func celestialReferenceDistanceKM(at time.Time, body CelestialBody) (float64, error) {
	switch body {
	case CelestialSun:
		return sunCoordinates(at).distance, nil
	case CelestialMoon:
		return moonCoordinates(at).distance, nil
	case CelestialMercury, CelestialVenus, CelestialMars, CelestialJupiter,
		CelestialSaturn, CelestialUranus, CelestialNeptune, CelestialPluto:
		coordinates, err := planetCoordinates(at, body)
		return coordinates.distance, err
	default:
		return 0, fmt.Errorf("unsupported celestial body %q", body)
	}
}

func distanceClosenessPercent(distance float64, scale CelestialDistanceScale) (float64, error) {
	if !finite(distance) || distance < scale.MinimumKM || distance > scale.MaximumKM {
		return 0, fmt.Errorf("distance %.9g km is outside the exhaustive hourly %s scale [%.9g, %.9g] km", distance, scale.ReferenceCenter, scale.MinimumKM, scale.MaximumKM)
	}
	value := 100 * (scale.MaximumKM - distance) / (scale.MaximumKM - scale.MinimumKM)
	return value, nil
}

func meanDistanceClosenessPercent(samples []CelestialHorizontalPosition) int {
	if len(samples) == 0 {
		return 0
	}
	sum := 0.0
	for _, sample := range samples {
		sum += sample.DistanceClosenessPercent
	}
	return int(math.Round(sum / float64(len(samples))))
}

func celestialRadialVelocityKMS(at time.Time, body CelestialBody) (float64, error) {
	left, right := at.Add(-30*time.Minute), at.Add(30*time.Minute)
	if left.Before(celestialEphemerisFirstInstant) {
		left, right = at, at.Add(time.Hour)
	}
	if !right.Before(celestialEphemerisLastInstant) {
		left, right = at.Add(-time.Hour), at
	}
	leftDistance, err := celestialReferenceDistanceKM(left, body)
	if err != nil {
		return 0, err
	}
	rightDistance, err := celestialReferenceDistanceKM(right, body)
	if err != nil {
		return 0, err
	}
	return (rightDistance - leftDistance) / right.Sub(left).Seconds(), nil
}

func topocentricHorizontal(at time.Time, location forecast.Location, coordinates equatorial) (float64, float64) {
	latitudeRadians := location.Latitude * degree
	rhoCosPhiPrime, rhoSinPhiPrime := wgs84ObserverFactors(location)
	sinHorizontalParallax := wgs84SemiMajorAxisKM / coordinates.distance
	hourAngle := localHourAngle(at, location.Longitude, coordinates.ra)

	a := math.Cos(coordinates.dec) * math.Sin(hourAngle)
	b := math.Cos(coordinates.dec)*math.Cos(hourAngle) - rhoCosPhiPrime*sinHorizontalParallax
	c := math.Sin(coordinates.dec) - rhoSinPhiPrime*sinHorizontalParallax
	norm := math.Sqrt(a*a + b*b + c*c)
	topocentricHourAngle := math.Atan2(a, b)
	topocentricDeclination := math.Asin(c / norm)

	altitudeRadians := altitude(topocentricHourAngle, latitudeRadians, topocentricDeclination)
	east := -math.Cos(topocentricDeclination) * math.Sin(topocentricHourAngle)
	north := math.Sin(topocentricDeclination)*math.Cos(latitudeRadians) -
		math.Cos(topocentricDeclination)*math.Cos(topocentricHourAngle)*math.Sin(latitudeRadians)
	return altitudeRadians, normalizeRadians(math.Atan2(east, north))
}

func wgs84ObserverFactors(location forecast.Location) (rhoCosPhiPrime, rhoSinPhiPrime float64) {
	latitudeRadians := location.Latitude * degree
	sinLatitude, cosLatitude := math.Sincos(latitudeRadians)
	primeVerticalRadiusKM := wgs84SemiMajorAxisKM /
		math.Sqrt(1-wgs84FirstEccentricitySquared*sinLatitude*sinLatitude)
	// The product currently has no observer-height input, so topocentric
	// parallax is evaluated on the WGS84 reference ellipsoid (h=0).
	return primeVerticalRadiusKM * cosLatitude / wgs84SemiMajorAxisKM,
		primeVerticalRadiusKM * (1 - wgs84FirstEccentricitySquared) * sinLatitude / wgs84SemiMajorAxisKM
}

func planningApparentAltitude(geometric float64) float64 {
	if geometric < -degree {
		return geometric
	}
	// Meeus/Bennett-style standard refraction. Unlike the legacy rise/set
	// helper, this path must retain the actual negative altitude down to the
	// published -1 degree applicability boundary instead of clamping it to the
	// geometric horizon.
	return geometric + 0.0002967/math.Tan(geometric+0.00312536/(geometric+0.08901179))
}

func normalizeRadians(value float64) float64 {
	value = math.Mod(value, 2*math.Pi)
	if value < 0 {
		value += 2 * math.Pi
	}
	return value
}
